modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/RidableBlazes/issues"
license="MIT"

[[mods]]
modId="ridableblazes"
version="${file.jarVersion}"
displayName="Ridable Blazes"
displayURL="https://minecraft.curseforge.com/projects/ridable-blazes"
authors="Mrbysco"
description='''

'''
[[dependencies.ridableblazes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.ridableblazes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"