modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/RideableBlazes/issues"
license="MIT"

[[mods]]
modId="rideableblazes"
version="${file.jarVersion}"
displayName="Rideable Blazes"
displayURL="https://minecraft.curseforge.com/projects/rideable-blazes"
authors="Mrbysco"
description='''

'''
[[dependencies.rideableblazes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.rideableblazes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"