modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/RidableBlazes/issues"
license="MIT"

[[mods]]
modId="ridableblazes"
version="${file.jarVersion}"
displayName="Ridable Blazes"
displayURL="https://minecraft.curseforge.com/projects/ridable-blazes"
authors="Mrbysco"
description='''

'''
[[dependencies.ridableblazes]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.ridableblazes]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.110-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="ridableblazes.mixins.json"